{% set name = "mne-connectivity" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 89f9e11d1843395dd67458f027aedee1a70fdfce97241a7d3f2710164d537864

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip

  run:
    - python >=3.9
    - mne-base >=1.6
    - numpy >=1.21
    - scipy >=1.5.0
    - pandas >=1.3.2
    - xarray >=2023.11.0
    - joblib >=1.0.0
    - netCDF4 >=1.6.5
    - h5netcdf
    - scikit-learn >=0.24.2
    - tqdm

test:
  imports:
    - mne_connectivity
    - mne_connectivity.viz
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://mne.tools/mne-connectivity
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Connectivity algorithms that leverage the MNE-Python API.
  description: |
    MNE-Connectivity is an open-source Python package for connectivity and
    related measures of MEG, EEG, or iEEG data built on top of the MNE-Python
    API. It includes modules for data input/output, visualization, common
    connectivity analysis, and post-hoc statistics and processing.
  dev_url: https://github.com/mne-tools/mne-connectivity

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
