{% set name = "mne-connectivity" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5c493dec1dd2dfcd89823adee939c7fb550b62c3a12771b9413e6511872668c4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - wheel
    - pip

  run:
    - python >={{ python_min }}
    - mne-base >=1.6
    - netcdf4 >=1.6.5
    - numpy >=1.21
    - pandas >=1.3.2
    - scikit-learn >=1.2
    - scipy >=1.4.0
    - tqdm
    - xarray >=2023.11.0
    - joblib >=1.0.0
    - h5netcdf

test:
  imports:
    - mne_connectivity
    - mne_connectivity.viz
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import mne_connectivity; assert mne_connectivity.__version__ == '{{ version }}', mne_connectivity.__version__"

about:
  home: https://mne.tools/mne-connectivity
  summary: 'mne-connectivity: A module for connectivity data analysis with MNE.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    MNE-Connectivity is an open-source Python package for connectivity and
    related measures of MEG, EEG, or iEEG data built on top of the MNE-Python
    API. It includes modules for data input/output, visualization, common
    connectivity analysis, and post-hoc statistics and processing.
  dev_url: https://github.com/mne-tools/mne-connectivity

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
